const { contextBridge, ipcRenderer } = require('electron');
let authToken = '';

contextBridge.exposeInMainWorld('ctgdmnDesktop', {
  getPublicBranding: () => ipcRenderer.invoke('branding:get-public'),
  getAuthStatus: () => ipcRenderer.invoke('auth:status'),
  setupFirstAdmin: (data) => ipcRenderer.invoke('auth:setup-first-admin', data),
  requestAccount: (data) => ipcRenderer.invoke('auth:request-account', data),
  login: async (username,password) => { const result=await ipcRenderer.invoke('auth:login',{username,password});authToken=result.token;return result.user; },
  logout: async () => { const result=await ipcRenderer.invoke('auth:logout',authToken);authToken='';return result; },
  changePassword: (currentPassword,newPassword) => ipcRenderer.invoke('auth:change-password',{token:authToken,currentPassword,newPassword}),
  listUsers: () => ipcRenderer.invoke('accounts:list',authToken),
  createUser: (data) => ipcRenderer.invoke('accounts:create',{token:authToken,data}),
  importUsers: (rows) => ipcRenderer.invoke('accounts:import',{token:authToken,rows}),
  lockUser: (userId,locked) => ipcRenderer.invoke('accounts:lock',{token:authToken,userId,locked}),
  resetUserPassword: (userId,tempPassword) => ipcRenderer.invoke('accounts:reset-password',{token:authToken,userId,tempPassword}),
  listAccountRequests: () => ipcRenderer.invoke('accounts:list-requests', authToken),
  approveAccountRequest: (requestId) => ipcRenderer.invoke('accounts:approve-request', {token:authToken,requestId}),
  rejectAccountRequest: (requestId,reason) => ipcRenderer.invoke('accounts:reject-request', {token:authToken,requestId,reason}),
  listChildren: () => ipcRenderer.invoke('children:list', authToken),
  upsertChild: (data) => ipcRenderer.invoke('children:upsert', {token:authToken,data}),
  deactivateChild: (childId) => ipcRenderer.invoke('children:deactivate', {token:authToken,childId}),
  listChildAssessments: (childId) => ipcRenderer.invoke('assessments:list', {token:authToken,childId}),
  upsertChildAssessment: (data) => ipcRenderer.invoke('assessments:upsert', {token:authToken,data}),
  deleteChildAssessment: (assessmentId) => ipcRenderer.invoke('assessments:delete', {token:authToken,assessmentId}),
  bootstrapRepository: (legacy) => ipcRenderer.invoke('repository:bootstrap',{token:authToken,legacy}),
  getRepositoryState: () => ipcRenderer.invoke('repository:get-state',authToken),
  saveRepositoryState: (payload) => ipcRenderer.invoke('repository:save-state',{token:authToken,payload}),
  transitionPlan: (planId,toStatus) => ipcRenderer.invoke('plans:transition',{token:authToken,planId,toStatus}),
  updateSystemConfig: (config) => ipcRenderer.invoke('repository:update-config',{token:authToken,config}),
  getAuditLog: (limit) => ipcRenderer.invoke('repository:audit',{token:authToken,limit}),
  createDatabaseBackup: () => ipcRenderer.invoke('repository:backup',authToken),
  restoreDatabaseBackup: (payload) => ipcRenderer.invoke('repository:restore',{token:authToken,payload}),
  listVideos: () => ipcRenderer.invoke('videos:list',authToken),
  saveVideo: (video) => ipcRenderer.invoke('videos:save',{token:authToken,video}),
  importOfflineVideo: (metadata) => ipcRenderer.invoke('videos:import-mp4',{token:authToken,metadata}),
  openOnlineVideo: (videoId) => ipcRenderer.invoke('videos:open-online',{token:authToken,videoId}),
  getOfflineVideoUrl: (videoId) => ipcRenderer.invoke('videos:get-offline-url',{token:authToken,videoId}),
  deleteVideo: (videoId) => ipcRenderer.invoke('videos:delete',{token:authToken,videoId}),
  openGuide: (format) => ipcRenderer.invoke('guides:open',{token:authToken,format}),
  openTrustedResource: (resourceId) => ipcRenderer.invoke('resources:open-trusted',{token:authToken,resourceId}),
  getProgramIndex: () => ipcRenderer.invoke('data:get-index'),
  getDocumentUrl: (relativePath) => ipcRenderer.invoke('documents:get-url', {token:authToken,relativePath}),
  openDocument: (relativePath) => ipcRenderer.invoke('documents:open', {token:authToken,relativePath}),
  chooseImportFiles: (kind) => ipcRenderer.invoke('imports:choose-files', {token:authToken,kind}),
  commitPdfImport: (tokens, actor) => ipcRenderer.invoke('imports:commit-pdf', { token:authToken,tokens, actor }),
  undoPdfImport: (relativePaths) => ipcRenderer.invoke('imports:undo-pdf', { token:authToken,relativePaths }),
  saveWord: (filename, type, payload, school) => ipcRenderer.invoke('exports:save-word', { token:authToken,filename, type, payload, school }),
  savePdf: (filename, payload, school) => ipcRenderer.invoke('exports:save-pdf', { token:authToken,filename, payload, school }),
  saveExcel: (filename, payload) => ipcRenderer.invoke('exports:save-excel', { token:authToken,filename, payload }),
  saveDirectoryExcel: (filename, kind, rows, template, school) => ipcRenderer.invoke('exports:save-directory', { token:authToken,filename, kind, rows, template, school }),
  getAIConfig: () => ipcRenderer.invoke('ai:get-config', authToken),
  saveAIConfig: (config) => ipcRenderer.invoke('ai:save-config', { token:authToken,config }),
  clearAIConfig: () => ipcRenderer.invoke('ai:clear-config', authToken),
  testAIConnection: () => ipcRenderer.invoke('ai:test-connection', authToken),
  runAI: (action, plan, requestId) => ipcRenderer.invoke('ai:generate', { token:authToken,action,plan,requestId }),
  cancelAI: (requestId) => ipcRenderer.invoke('ai:cancel', { token:authToken,requestId }),
  listTemplates: () => ipcRenderer.invoke('templates:list', authToken),
  importTemplate: (metadata) => ipcRenderer.invoke('templates:import', { token:authToken,metadata }),
  setDefaultTemplate: (type,templateId) => ipcRenderer.invoke('templates:set-default', { token:authToken,type,templateId }),
  backupTemplates: () => ipcRenderer.invoke('templates:backup', authToken),
  restoreTemplates: () => ipcRenderer.invoke('templates:restore', authToken),
  platform: process.platform,
});
