const { DatabaseSync } = require('node:sqlite');
const crypto=require('crypto');
const { hashPassword,verifyPassword,authorize,sanitizeAuditDetails,scopeAllows,transitionPlan,ROLES }=require('./security.cjs');
const iso=()=>new Date().toISOString();

class Repository {
  constructor(filePath){this.db=new DatabaseSync(filePath);this.sessions=new Map();this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
    CREATE TABLE IF NOT EXISTS app_state(key TEXT PRIMARY KEY,value_json TEXT NOT NULL,updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,full_name TEXT NOT NULL,staff_id TEXT,title TEXT,team TEXT,class_ids_json TEXT NOT NULL,roles_json TEXT NOT NULL,scope_json TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,password_hash TEXT NOT NULL,must_change_password INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,last_login_at TEXT,created_by TEXT);
    CREATE TABLE IF NOT EXISTS audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT,created_at TEXT NOT NULL,action TEXT NOT NULL,target_type TEXT,target_id TEXT,version INTEGER,result TEXT NOT NULL,details_json TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS videos(id TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT,category TEXT NOT NULL,audience_json TEXT NOT NULL,thumbnail TEXT,source_type TEXT NOT NULL,url TEXT,local_path TEXT,duration TEXT,sort_order INTEGER NOT NULL DEFAULT 0,enabled INTEGER NOT NULL DEFAULT 1,context_key TEXT,updated_at TEXT NOT NULL,updated_by TEXT,used_count INTEGER NOT NULL DEFAULT 0);
    CREATE TABLE IF NOT EXISTS account_requests(id TEXT PRIMARY KEY,full_name TEXT NOT NULL,username TEXT NOT NULL,password_hash TEXT NOT NULL,title TEXT,team TEXT,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL,decided_at TEXT,decided_by TEXT,reject_reason TEXT);`);this.seedBuiltinResources();}
  seedBuiltinResources(){const version=Number(this.getJson('builtinResourceVersion',0));if(version>=1)return;this.db.prepare('INSERT OR IGNORE INTO videos(id,title,description,category,audience_json,thumbnail,source_type,url,local_path,duration,sort_order,enabled,context_key,updated_at,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('builtin-video-ctgdmn-guide','Video hướng dẫn sử dụng Trường Mầm non Số','Video hướng dẫn trực tuyến dành cho giáo viên và cán bộ quản lý khi bắt đầu sử dụng ứng dụng.','Bắt đầu sử dụng','[]','','online','https://www.youtube.com/watch?v=P5DgJHPLkDk',null,'',10,1,'',iso(),'system');this.setJson('builtinResourceVersion',1);}
  close(){this.db.close();}
  hasUsers(){return this.db.prepare('SELECT COUNT(*) AS n FROM users').get().n>0;}
  audit(userId,action,targetType='',targetId='',version=0,result='success',details={}){this.db.prepare('INSERT INTO audit_log(user_id,created_at,action,target_type,target_id,version,result,details_json) VALUES(?,?,?,?,?,?,?,?)').run(userId||null,iso(),action,targetType,targetId||null,Number(version)||0,result,JSON.stringify(sanitizeAuditDetails(details)));}
  createFirstAdmin(data){if(this.hasUsers())throw new Error('Tài khoản quản trị đầu tiên đã được thiết lập.');return this._insertUser(null,{...data,roles:[ROLES.ADMIN],mustChangePassword:false});}
  _insertUser(actor,data){const username=String(data.username||'').trim().toLowerCase();if(!/^[a-z0-9._-]{3,40}$/.test(username))throw new Error('Tên đăng nhập phải có 3–40 ký tự không dấu.');const user={id:`user-${crypto.randomUUID()}`,username,fullName:String(data.fullName||'').trim(),staffId:data.staffId||'',title:data.title||'',team:data.team||'',classIds:data.classIds||[],roles:data.roles||[ROLES.VIEWER],scope:data.scope||{},active:true,mustChangePassword:data.mustChangePassword!==false,createdAt:iso(),createdBy:actor?.id||''};if(!user.fullName)throw new Error('Họ và tên là bắt buộc.');const passwordHash=data.passwordHash||hashPassword(data.password);this.db.prepare('INSERT INTO users(id,username,full_name,staff_id,title,team,class_ids_json,roles_json,scope_json,active,password_hash,must_change_password,created_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(user.id,user.username,user.fullName,user.staffId,user.title,user.team,JSON.stringify(user.classIds),JSON.stringify(user.roles),JSON.stringify(user.scope),1,passwordHash,user.mustChangePassword?1:0,user.createdAt,user.createdBy);this.audit(actor?.id,'account.create','user',user.id,0,'success',{username});return user;}
  createUser(actor,data){authorize(actor,'accounts.manage');return this._insertUser(actor,data);}
  importUsers(actor,rows){authorize(actor,'accounts.manage');if(!Array.isArray(rows)||!rows.length)throw new Error('Tệp Excel không có tài khoản hợp lệ.');if(rows.length>500)throw new Error('Mỗi lần chỉ được nhập tối đa 500 tài khoản.');const allowedRoles=new Set([ROLES.PRINCIPAL,ROLES.VICE,ROLES.LEAD,ROLES.TEACHER,ROLES.VIEWER]);const result={created:0,skipped:0,errors:[]};for(let index=0;index<rows.length;index+=1){const row=rows[index]||{};const username=String(row.username||'').trim().toLowerCase();try{const roles=Array.isArray(row.roles)?[...new Set(row.roles.map((role)=>String(role).trim()).filter(Boolean))]:[];if(!roles.length||roles.some((role)=>!allowedRoles.has(role)))throw new Error('Vai trò không hợp lệ hoặc không được phép nhập hàng loạt.');if(this.db.prepare('SELECT 1 FROM users WHERE username=?').get(username)){result.skipped+=1;continue;}this._insertUser(actor,{username,fullName:String(row.fullName||'').trim().slice(0,120),password:String(row.password||''),title:String(row.title||'').trim().slice(0,120),team:String(row.team||'').trim().slice(0,240),roles,classIds:[],scope:{},mustChangePassword:true});result.created+=1;}catch(error){result.errors.push({row:index+2,username,error:error.message});}}this.audit(actor.id,'account.import','user','multiple',0,result.errors.length?'partial':'success',{created:result.created,skipped:result.skipped,errors:result.errors.length});return result;}
  rowUser(row){if(!row)return null;return{id:row.id,username:row.username,fullName:row.full_name,staffId:row.staff_id,title:row.title,team:row.team,classIds:JSON.parse(row.class_ids_json),roles:JSON.parse(row.roles_json),scope:JSON.parse(row.scope_json),active:Boolean(row.active),mustChangePassword:Boolean(row.must_change_password),createdAt:row.created_at,lastLoginAt:row.last_login_at,createdBy:row.created_by};}
  listUsers(actor){authorize(actor,'accounts.manage');return this.db.prepare('SELECT * FROM users ORDER BY full_name').all().map((row)=>this.rowUser(row));}
  login(username,password){const row=this.db.prepare('SELECT * FROM users WHERE username=?').get(String(username||'').trim().toLowerCase());if(!row||!row.active||!verifyPassword(password,row.password_hash)){this.audit(row?.id,'auth.login','user',row?.id,0,'failed',{username:String(username||'').trim().toLowerCase()});throw new Error('Tên đăng nhập hoặc mật khẩu không đúng.');}const token=crypto.randomBytes(32).toString('hex');const user=this.rowUser(row);this.sessions.set(token,{user,lastActivity:Date.now()});this.db.prepare('UPDATE users SET last_login_at=? WHERE id=?').run(iso(),row.id);this.audit(row.id,'auth.login','user',row.id);return{token,user};}
  session(token,idleMinutes=30){const session=this.sessions.get(token);if(!session)throw new Error('Phiên đăng nhập không hợp lệ.');if(Date.now()-session.lastActivity>idleMinutes*60000){this.sessions.delete(token);throw new Error('Phiên đăng nhập đã hết hạn do không hoạt động.');}session.lastActivity=Date.now();return session.user;}
  logout(token){const session=this.sessions.get(token);if(session)this.audit(session.user.id,'auth.logout','user',session.user.id);this.sessions.delete(token);}
  changePassword(user,current,next){const row=this.db.prepare('SELECT password_hash FROM users WHERE id=?').get(user.id);if(!verifyPassword(current,row.password_hash))throw new Error('Mật khẩu hiện tại không đúng.');this.db.prepare('UPDATE users SET password_hash=?,must_change_password=0 WHERE id=?').run(hashPassword(next),user.id);this.audit(user.id,'account.password_change','user',user.id);}
  resetPassword(actor,userId,temp){authorize(actor,'accounts.manage');this.db.prepare('UPDATE users SET password_hash=?,must_change_password=1 WHERE id=?').run(hashPassword(temp),userId);this.audit(actor.id,'account.password_reset','user',userId);}
  lockUser(actor,userId,locked){authorize(actor,'accounts.manage');if(actor.id===userId&&locked)throw new Error('Không thể tự khóa tài khoản đang đăng nhập.');this.db.prepare('UPDATE users SET active=? WHERE id=?').run(locked?0:1,userId);this.audit(actor.id,locked?'account.lock':'account.unlock','user',userId);}
  requestAccount(data){
    const username=String(data.username||'').trim().toLowerCase();
    if(!/^[a-z0-9._-]{3,40}$/.test(username))throw new Error('Tên đăng nhập phải có 3–40 ký tự không dấu.');
    const fullName=String(data.fullName||'').trim();
    if(!fullName)throw new Error('Họ và tên là bắt buộc.');
    if(this.db.prepare('SELECT 1 FROM users WHERE username=?').get(username))throw new Error('Tên đăng nhập đã được sử dụng.');
    if(this.db.prepare("SELECT 1 FROM account_requests WHERE username=? AND status='pending'").get(username))throw new Error('Tên đăng nhập này đang có một yêu cầu chờ duyệt.');
    const passwordHash=hashPassword(data.password);
    const id=`request-${crypto.randomUUID()}`;
    this.db.prepare('INSERT INTO account_requests(id,full_name,username,password_hash,title,team,status,created_at) VALUES(?,?,?,?,?,?,?,?)')
      .run(id,fullName,username,passwordHash,String(data.title||'').trim(),String(data.team||'').trim(),'pending',iso());
    this.audit(null,'account.request','account_request',id,0,'success',{username});
    return {ok:true};
  }
  listAccountRequests(actor){
    authorize(actor,'accounts.manage');
    return this.db.prepare("SELECT id,full_name AS fullName,username,title,team,status,created_at AS createdAt FROM account_requests WHERE status='pending' ORDER BY created_at").all();
  }
  approveAccountRequest(actor,requestId){
    authorize(actor,'accounts.manage');
    const request=this.db.prepare("SELECT * FROM account_requests WHERE id=? AND status='pending'").get(requestId);
    if(!request)throw new Error('Không tìm thấy yêu cầu đang chờ duyệt.');
    if(this.db.prepare('SELECT 1 FROM users WHERE username=?').get(request.username))throw new Error('Tên đăng nhập đã được người khác sử dụng, không thể duyệt yêu cầu này.');
    const user=this._insertUser(actor,{username:request.username,fullName:request.full_name,passwordHash:request.password_hash,title:request.title,team:request.team,roles:[ROLES.TEACHER],mustChangePassword:false});
    this.db.prepare("UPDATE account_requests SET status='approved',decided_at=?,decided_by=? WHERE id=?").run(iso(),actor.id,requestId);
    this.audit(actor.id,'account.request_approve','account_request',requestId,0,'success',{username:request.username});
    return user;
  }
  rejectAccountRequest(actor,requestId,reason){
    authorize(actor,'accounts.manage');
    const request=this.db.prepare("SELECT * FROM account_requests WHERE id=? AND status='pending'").get(requestId);
    if(!request)throw new Error('Không tìm thấy yêu cầu đang chờ duyệt.');
    this.db.prepare("UPDATE account_requests SET status='rejected',decided_at=?,decided_by=?,reject_reason=? WHERE id=?").run(iso(),actor.id,String(reason||'').trim(),requestId);
    this.audit(actor.id,'account.request_reject','account_request',requestId,0,'success',{username:request.username});
    return {ok:true};
  }
  getJson(key,fallback){const row=this.db.prepare('SELECT value_json FROM app_state WHERE key=?').get(key);return row?JSON.parse(row.value_json):fallback;}
  getPublicBranding(){const school=this.getJson('workspace',{})?.schoolProfile||{};return{schoolName:String(school.name||'').trim()||'Trường Mầm non Số',schoolYear:String(school.schoolYear||'').trim()||'2026–2027'};}
  setJson(key,value){this.db.prepare('INSERT INTO app_state(key,value_json,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at').run(key,JSON.stringify(value),iso());}
  bootstrapLegacy(legacy={}){let workspace=this.getJson('workspace',null);if(!workspace){workspace=legacy.workspace||{};this.setJson('review',legacy.review||{});this.setJson('systemConfig',{repositoryMode:'local',serverUrl:'',idleMinutes:30,migratedAt:iso()});}const schoolId=workspace.schoolProfile?.id||'school-main';workspace={edits:{},customRecords:[],plans:[],sourceDocuments:[],importHistory:[],importLog:[],classes:[],staff:[],professionalReviews:[],signatures:[],signatureLog:[],planVersions:[],publicationSnapshots:[],planStatusHistory:[],...workspace,schemaVersion:4};workspace.plans=(workspace.plans||[]).map((plan)=>({version:1,workflowStatus:'draft',schoolId,classId:'',authorTeacherId:'',collaboratingTeacherIds:[],reviewerIds:[],approverId:'',signatureConfigurationIds:[],...plan}));this.setJson('workspace',workspace);this.audit(null,'migration.localStorage','workspace','main',4,'success',{hadWorkspace:Boolean(legacy.workspace)});return true;}
  getState(user){authorize(user,user.roles.includes(ROLES.ADMIN)?'data.manage':user.roles.includes(ROLES.VIEWER)?'data.read_shared':'data.read');const workspace=this.getJson('workspace',{});const full=user.roles.includes(ROLES.ADMIN)||user.roles.includes(ROLES.PRINCIPAL);if(!full){const staff=workspace.staff||[];const plans=(workspace.plans||[]).filter((plan)=>{const author=staff.find((person)=>person.id===plan.authorTeacherId);return scopeAllows(user,{...plan,team:plan.team||author?.team});});const ids=new Set(plans.map((plan)=>plan.id));workspace.plans=plans;workspace.planVersions=(workspace.planVersions||[]).filter((plan)=>ids.has(plan.id));workspace.professionalReviews=(workspace.professionalReviews||[]).filter((review)=>ids.has(review.planId));workspace.publicationSnapshots=(workspace.publicationSnapshots||[]).filter((snapshot)=>ids.has(snapshot.planId));workspace.signatures=(workspace.signatures||[]).map((signature)=>signature.staffId===user.staffId?signature:{...signature,imageData:''});}return{workspace,review:this.getJson('review',{}),systemConfig:this.getJson('systemConfig',{repositoryMode:'local',idleMinutes:30})};}
  saveState(user,payload){authorize(user,user.roles.includes(ROLES.ADMIN)?'data.manage':'data.read');const old=this.getJson('workspace',{});const next=payload.workspace||{};if(user.roles.includes(ROLES.VIEWER))throw new Error('Người xem không được sửa dữ liệu.');const admin=user.roles.includes(ROLES.ADMIN);if(!admin)for(const key of ['schoolProfile','classes','staff','signatures','customRecords','edits','sourceDocuments'])if(JSON.stringify(old[key]||null)!==JSON.stringify(next[key]||null))throw new Error('Bạn không được thay đổi cấu hình hoặc kho dữ liệu quản trị.');if(user.roles.includes(ROLES.TEACHER)&&!user.roles.some((r)=>[ROLES.ADMIN,ROLES.PRINCIPAL,ROLES.VICE,ROLES.LEAD].includes(r)))for(const plan of next.plans||[]){const previous=(old.plans||[]).find((p)=>p.id===plan.id);if(JSON.stringify(previous)!==JSON.stringify(plan)&&plan.authorTeacherId!==user.staffId)throw new Error('Giáo viên chỉ được sửa kế hoạch của mình.');if(previous&&previous.workflowStatus&&!['draft','changes_requested'].includes(previous.workflowStatus)&&JSON.stringify(previous)!==JSON.stringify(plan))throw new Error('Bản kế hoạch đang gửi đã bị khóa.');}let saved=next;if(!admin){saved={...old};const planMap=new Map((old.plans||[]).map((plan)=>[plan.id,plan]));for(const plan of next.plans||[])planMap.set(plan.id,plan);saved.plans=[...planMap.values()];const reviewMap=new Map((old.professionalReviews||[]).map((review)=>[review.id,review]));for(const review of next.professionalReviews||[])reviewMap.set(review.id,review);saved.professionalReviews=[...reviewMap.values()];for(const key of ['planVersions','publicationSnapshots','signatureLog','importHistory','importLog'])if(next[key])saved[key]=next[key];}this.setJson('workspace',saved);this.setJson('review',payload.review||{});this.audit(user.id,payload.action||'data.update',payload.targetType||'workspace',payload.targetId||'main',payload.version||0);return true;}
  transition(user,planId,toStatus){const workspace=this.getJson('workspace',{});const index=(workspace.plans||[]).findIndex((plan)=>plan.id===planId);if(index<0)throw new Error('Không tìm thấy kế hoạch.');const previous=workspace.plans[index];const author=(workspace.staff||[]).find((person)=>person.id===previous.authorTeacherId);const changed=transitionPlan(user,{...previous,team:previous.team||author?.team},toStatus);workspace.plans[index]=changed;workspace.planStatusHistory=[...(workspace.planStatusHistory||[]),{id:`status-${crypto.randomUUID()}`,planId,planVersion:changed.version,fromStatus:previous.workflowStatus||'draft',toStatus,actorUserId:user.id,createdAt:iso()}];this.setJson('workspace',workspace);this.audit(user.id,'plan.transition','plan',planId,changed.version,'success',{from:previous.workflowStatus||'draft',to:toStatus});return changed;}
  updateConfig(actor,config){authorize(actor,'school.configure');const old=this.getJson('systemConfig',{});this.setJson('systemConfig',{...old,...config});this.audit(actor.id,'system.configure','config','main');}
  createBackup(actor){authorize(actor,'backup.manage');const users=this.db.prepare('SELECT * FROM users').all();const payload={format:'ctgdmn-sqlite-backup',version:4,exportedAt:iso(),state:{workspace:this.getJson('workspace',{}),review:this.getJson('review',{}),systemConfig:this.getJson('systemConfig',{})},users};this.audit(actor.id,'backup.export','database','main');return payload;}
  restoreBackup(actor,payload){authorize(actor,'backup.manage');if(payload?.format!=='ctgdmn-sqlite-backup'||!payload.state||!Array.isArray(payload.users))throw new Error('Tệp sao lưu không hợp lệ.');this.db.exec('BEGIN IMMEDIATE');try{this.setJson('workspace',payload.state.workspace||{});this.setJson('review',payload.state.review||{});this.setJson('systemConfig',payload.state.systemConfig||{});const statement=this.db.prepare('INSERT OR REPLACE INTO users(id,username,full_name,staff_id,title,team,class_ids_json,roles_json,scope_json,active,password_hash,must_change_password,created_at,last_login_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');for(const row of payload.users){if(!String(row.password_hash||'').startsWith('scrypt$'))throw new Error('Bản sao lưu chứa thông tin xác thực không hợp lệ.');statement.run(row.id,row.username,row.full_name,row.staff_id,row.title,row.team,row.class_ids_json,row.roles_json,row.scope_json,row.active,row.password_hash,row.must_change_password,row.created_at,row.last_login_at,row.created_by);}this.db.exec('COMMIT');}catch(error){this.db.exec('ROLLBACK');throw error;}this.audit(actor.id,'backup.restore','database','main');return true;}
  auditRows(actor,limit=500){authorize(actor,'audit.view');return this.db.prepare('SELECT * FROM audit_log ORDER BY id DESC LIMIT ?').all(Math.min(1000,Number(limit)||500)).map((row)=>({...row,details:JSON.parse(row.details_json)}));}
}
module.exports={Repository};
